#!/usr/bin/python3

#Convert .hex file generated by icebram to .bin file 


from sys import argv

hexfile = argv[1]
binfile = argv[2]


with open(hexfile,"r") as input_file:
    lines = list(input_file)


output_file = open(binfile,"w") 

for line in lines :
    bn = format(int(line, 16), "08b")
    output_file.write(bn + "\n")


input_file.close()
output_file.close()


