/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/stche/Documents/Projets/FPGA/FpgaRiscV/data/TangPrimer/al_ip/EG4S20SDRAM.v
 ** Date	:	2021 12 21
 ** TD version	:	5.0.43066
\************************************************************/

`timescale 1ns / 1ps

module EG4S20SDRAM ( clk, ras_n, cas_n, we_n, addr, ba, dq_read,dq_write,dq_writeEnable, cs_n, dm0, dm1, dm2, dm3, cke );
	input  		clk;
	input  		ras_n;
	input  		cas_n;
	input  		we_n;
	input  		[10:0] addr;
	input  		[1:0] ba;
    output 		[31:0] dq_read;
    input		[31:0] dq_write;
    input       [31:0] dq_writeEnable;	
    
	//inout  		[31:0] dq;
	input  		cs_n;
	input  		dm0;
	input  		dm1;
	input  		dm2;
	input  		dm3;
	input  		cke;

   wire [31:0] sdram_dq;
   
   assign sdram_dq = we_n ?  'hz  : dq_write;
   
   assign dq_read = sdram_dq;
  

	EG_PHY_SDRAM_2M_32 sdram(
		.clk(clk),
		.ras_n(ras_n),
		.cas_n(cas_n),
		.we_n(we_n),
		.addr(addr),
		.ba(ba),
		.dq(sdram_dq),
		.cs_n(cs_n),
		.dm0(dm0),
		.dm1(dm1),
		.dm2(dm2),
		.dm3(dm3),
		.cke(cke));

endmodule